# Generated by Django 5.1 on 2024-08-18 03:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="descrption",
            new_name="description",
        ),
    ]
