# Generated by Django 5.1 on 2024-09-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_ticket_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="used",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
