# Generated by Django 5.1 on 2024-09-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_ticket_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity_actual',
            field=models.IntegerField(default=50),
        ),
    ]
