# Generated by Django 5.1 on 2024-09-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_capacity_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity_updated',
            field=models.BooleanField(default=False),
        ),
    ]
