# Generated by Django 5.1 on 2024-09-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_capacity_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity_actual',
            field=models.IntegerField(default=0),
        ),
    ]
